'use strict';

module.exports = {
    SEND: 0,
    SIGNATURE: 1,
    DELEGATE: 2,
    VOTE: 3,
    MULTI: 4,
    DAPP: 5,
    IN_TRANSFER: 6,
    OUT_TRANSFER: 7,
    IPFS: 8,

    // UIA: USER ISSUE ASSET
    UIA_ISSUER: 9, // UIA ISSUER REGISTER
    UIA_ASSET: 10, // UIA ASSET REGISTER
    UIA_FLAGS: 11, // UIA FLAGS UPDATE
    UIA_ACL: 12, // UIA ACL UPDATE
    UIA_ISSUE: 13, // UIA ISSUE
    UIA_TRANSFER: 14, // UIA TRANSFER
};
